# Generated by Django 5.1.2 on 2024-11-11 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdata',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='jobdata',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
            preserve_default=False,
        ),
    ]
