# Generated by Django 5.1.2 on 2024-11-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobdata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city2', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('notice_period', models.CharField(max_length=30)),
                ('expected_salarly', models.CharField(max_length=30)),
                ('upload_file', models.FileField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
        migrations.CreateModel(
            name='TrainersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city2', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('notice_period', models.CharField(max_length=30)),
                ('expected_salarly', models.CharField(max_length=30)),
                ('upload_file', models.FileField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
