# Generated by Django 5.1.2 on 2024-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_employerdata_city2_remove_trainersdata_city2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekers',
            name='name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='phone',
            field=models.IntegerField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
