# Generated by Django 5.1.2 on 2024-11-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobseekers_name_jobseekers_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainersdata',
            old_name='expected_salarly',
            new_name='expert',
        ),
        migrations.RemoveField(
            model_name='trainersdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trainersdata',
            name='district',
        ),
        migrations.RemoveField(
            model_name='trainersdata',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='trainersdata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='trainersdata',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='trainersdata',
            name='contact',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainersdata',
            name='linkedin',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainersdata',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainersdata',
            name='website',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseekers',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
