# Generated by Django 5.1.2 on 2024-11-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_employerdata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersdata',
            name='website',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
