# Generated by Django 5.1.2 on 2024-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_trainersdata_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersdata',
            name='website',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
