# Generated by Django 5.1.2 on 2024-11-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_trainersdata_website'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerData',
            new_name='Employers',
        ),
        migrations.RenameModel(
            old_name='TrainersData',
            new_name='Trainers',
        ),
    ]
