# Generated by Django 5.1.2 on 2024-11-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_employerdata_employers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataForm',
            new_name='Contact',
        ),
    ]
