# Generated by Django 5.1.2 on 2024-11-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_dataform_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city2', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('notice_period', models.CharField(max_length=30)),
                ('expected_salarly', models.CharField(max_length=30)),
                ('upload_file', models.FileField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Employers',
        ),
        migrations.RemoveField(
            model_name='jobseekers',
            name='district',
        ),
        migrations.RemoveField(
            model_name='jobseekers',
            name='state',
        ),
        migrations.DeleteModel(
            name='Trainers',
        ),
        migrations.DeleteModel(
            name='JobSeekers',
        ),
    ]
