# Generated by Django 5.1.1 on 2024-11-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_jobdata_jobseekers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekers',
            old_name='expected_salarly',
            new_name='expected_salary',
        ),
    ]
