# Generated by Django 5.1.1 on 2024-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_expected_salarly_jobseekers_expected_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.CharField(max_length=30)),
                ('expert', models.CharField(max_length=33)),
            ],
        ),
    ]
