# Generated by Django 5.1.1 on 2024-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_trainers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('website', models.CharField(blank=True, max_length=20, null=True)),
                ('requirements', models.CharField(max_length=50)),
            ],
        ),
    ]
