# Generated by Django 5.1.1 on 2024-11-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_employers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataForm',
            new_name='Contact',
        ),
    ]
